refactor: Simplify release workflow
This commit simplifies the release workflow by renaming a job, removing unnecessary steps, and improving the branch and pre-release checks. The workflow now checks if the release is on the master branch and if it is a pre-release before proceeding with the build steps. It also sets the latest tag to the release tag for both GHCR and Docker Hub builds.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ env:
   IMAGE_TAG: latest
 
 jobs:
-  clear:
+  before_build:
     runs-on: ubuntu-latest
     steps:
       # Clear the digests from the artifacts
@@ -26,65 +26,31 @@ jobs:
             digests_dh
             digests_ghcr
 
-  prerelease:
-    name: Check if release is not a pre-release
-    runs-on: ubuntu-latest
-    needs:
-      - clear
-    steps:
-      # If the release is a pre-release, succeed the job
-      - name: Check if release is not a pre-release
-        run: |
-          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
-            echo "Release is a pre-release. Skipping."
-            exit 1
-          else
-            echo "Release is not a pre-release. Continuing."
-          fi
-
-  master_branch:
-    name: Check if release is on master branch
-    runs-on: ubuntu-latest
-    needs:
-      - prerelease
-    steps:
-      # If the release is not on the master branch, succeed the job
+      # Only run the workflow if the release is on the master branch
       - name: Check if release is on master branch
         run: |
-          if [[ "${{ github.event.release.target_commitish }}" != "master" ]]; then
-            echo "Release is not on master branch. Skipping."
-            exit 1
+          if [ "${{ github.event.release.prerelease }}" != true ]; then
+            echo "Release is not a pre-release. Continuing."
           else
-            echo "Release is on master branch. Continuing."
+            echo "Release is a pre-release. Skipping workflow."
+            exit 78 # Exit with a neutral exit code (78) to indicate a skipped workflow.
           fi
 
-  update_latest:
-    runs-on: ubuntu-latest
-    needs:
-      - master_branch
-    permissions:
-      contents: write
-    steps:
-      # Checkout the repo and the translations branch
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      # Update latest file with the new version number
-      - name: Update latest file
+      # Only run the workflow if the release is on the master branch
+      - name: Check if release is on master branch
         run: |
-          echo "${{ github.event.release.tag_name }}" > latest
-
-      # Commit and push changes
-      - uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-          commit_message: "Update latest file"
-          file_pattern: "latest"
+          if [ "${{ github.event.release.target_commitish }}" = "master" ]; then
+            echo "Release is on the master branch."
+          else
+            echo "Release is not on the master branch. Skipping workflow."
+            exit 78 # Exit with a neutral exit code (78) to indicate a skipped workflow.
+          fi
 
   build_ghcr:
     name: Build Digest for GHCR
     runs-on: ubuntu-latest
     needs:
-      - update_latest
+      - before_build
     strategy:
       fail-fast: false
       matrix:
@@ -96,6 +62,11 @@ jobs:
       # Checkout the repo
       - name: Checkout
         uses: actions/checkout@v4
+
+      # Set the latest tag to the release tag
+      - name: Set latest tag
+        run: |
+          echo "${{ github.event.release.tag_name }}" > latest
 
       # Get the Metadata from the Docker Image
       - name: Docker meta
@@ -199,7 +170,7 @@ jobs:
     name: Build Digest for Docker Hub
     runs-on: ubuntu-latest
     needs:
-      - update_latest
+      - before_build
     strategy:
       fail-fast: false
       matrix:
@@ -211,6 +182,11 @@ jobs:
       # Checkout the repo
       - name: Checkout
         uses: actions/checkout@v4
+
+      # Set the latest tag to the release tag
+      - name: Set latest tag
+        run: |
+          echo "${{ github.event.release.tag_name }}" > latest
 
       # Get the Metadata from the Docker Image
       - name: Docker meta
